version: "3.3"

services:
  bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CIVICS_DB_HOST=db
    networks:
      - civics
    hostname: bot

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - civics
    hostname: db

networks:
  civics:
